### ISSUE TITLE
Update for DR3

### ISSUE THREAD

**Issue by rainwoodman** [desihub/imaginglss#16]
[ ] Move the cache to DESI project directory.
[ ] Move the public catalogue to DESI project directory
[ ] Include NEXP in RANDOMs.

Probably also include GALDEPTH in RANDOMs.

**Comment by rainwoodman** [comment]
![index](https://cloud.githubusercontent.com/assets/138060/18366412/6a016e48-75cb-11e6-84b2-98635612f4b4.png)

**Comment by guotsuan** [comment]
Hi,

I'm wondering, by any chance, if the supporting of DR3 is ready for the public to use ? 

Best regards,

**Comment by rainwoodman** [comment]
All three items were done.
