### ISSUE TITLE
Travis-CI.

### ISSUE THREAD

**Issue by rainwoodman** [desihub/imaginglss#8]
Before going 0.1.0 / pypi. 

We need to have some travis-CI tests integrated. Since the DR2 subset data is already uploaded on Amazon, it wouldn't be hard. I will take care of this.

**Comment by rainwoodman** [comment]
@sbailey Could you enable travisCi for imaginglss at travis site? It doesn't seem to be responding to my commit to .travis.yml

**Comment by weaverba137** [comment]
Should be set up now.  Try another commit.

**Comment by rainwoodman** [comment]
Thanks!
